#!/bin/bash

if [ -d "$2" ]; then
   
   if [ ! -d "$3" ]; then
   mkdir "$3"
   for file in "$2"/*; do
      if [ "$1" == "-f" ]; then
         if [ -f "$file" ]; then
         fname="$3/${file##*/}"
         echo "$file -> $fname"
         cp "$file" "$fname"
         fi
      elif [ "$1" == "-d" ]; then
         if [ -d "$file" ]; then
            dirname="$3/${file##*/}"
            echo "$file -> $dirname"
            bash $0 $1 "$file" "$dirname"
         fi 

      elif [ "$1" == "-l" ]; then
         if [ -L "$file" ]; then
            fname="$3/${file##*/}"
            echo "$file -> $fname"
            cp "$file" "$fname"
         fi
      fi
   done
   else
      echo "Directorul destinatie exista deja"
   fi
else
echo "Directorul sursa nu exista."
fi